### ISSUE TITLE
Please update Node.js to supported version - Node 12 LTS is EoL

### ISSUE THREAD

**Issue by jamacku** [fedora-ci/ciboard#62]
Support of Node 12 LTS ended on _30 Apr 2022_

Currently supported LTS versions:

- Node 14 LTS - supported till _30 Apr 2023_
- Node 16 LTS - supported till _11 Sep 2023_
- Node 18 LTS - supported till _30 Apr 2025_

**Comment by mgrabovsky** [comment]
What does this entail? What changes are required from our side?

**Comment by jamacku** [comment]
I think the following PR fixed the issue:
- https://github.com/fedora-ci/ciboard/pull/80

But it would be nice if CI could also be updated to use Node 18 (currently it uses Node 14)
